workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Plex-Spec:
        inputs:
            - location: https://raw.githubusercontent.com/LukeHagar/plex-api-spec/main/plex-media-server-spec-dereferenced.yaml
targets:
    Postman:
        target: postman
        source: Plex-Spec
